# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ul_srs_est.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='ul_srs_est.proto',
  package='NRpose',
  syntax='proto2',
  serialized_pb=_b('\n\x10ul_srs_est.proto\x12\x06NRpose\"\x86\x01\n\x0bNR_SRS_PACK\x12\'\n\nESTIMATION\x18\x01 \x03(\x0b\x32\x13.NRpose.NR_SRS_INFO\x12\x14\n\x0cSIGNAL_POWER\x18\x02 \x02(\x05\x12\x13\n\x0bNOISE_POWER\x18\x03 \x02(\x05\x12\x11\n\tCALL_TIME\x18\x05 \x02(\x05\x12\x10\n\x08\x46UNC_CNT\x18\x06 \x02(\x05\"-\n\x0bNR_SRS_INFO\x12\x1e\n\x06LS_SRS\x18\x03 \x03(\x0b\x32\x0e.NRpose.RESULT\"%\n\x06RESULT\x12\r\n\x05image\x18\x01 \x02(\x05\x12\x0c\n\x04real\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_NR_SRS_PACK = _descriptor.Descriptor(
  name='NR_SRS_PACK',
  full_name='NRpose.NR_SRS_PACK',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ESTIMATION', full_name='NRpose.NR_SRS_PACK.ESTIMATION', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='SIGNAL_POWER', full_name='NRpose.NR_SRS_PACK.SIGNAL_POWER', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='NOISE_POWER', full_name='NRpose.NR_SRS_PACK.NOISE_POWER', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='CALL_TIME', full_name='NRpose.NR_SRS_PACK.CALL_TIME', index=3,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='FUNC_CNT', full_name='NRpose.NR_SRS_PACK.FUNC_CNT', index=4,
      number=6, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=163,
)


_NR_SRS_INFO = _descriptor.Descriptor(
  name='NR_SRS_INFO',
  full_name='NRpose.NR_SRS_INFO',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='LS_SRS', full_name='NRpose.NR_SRS_INFO.LS_SRS', index=0,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=165,
  serialized_end=210,
)


_RESULT = _descriptor.Descriptor(
  name='RESULT',
  full_name='NRpose.RESULT',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image', full_name='NRpose.RESULT.image', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='real', full_name='NRpose.RESULT.real', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=212,
  serialized_end=249,
)

_NR_SRS_PACK.fields_by_name['ESTIMATION'].message_type = _NR_SRS_INFO
_NR_SRS_INFO.fields_by_name['LS_SRS'].message_type = _RESULT
DESCRIPTOR.message_types_by_name['NR_SRS_PACK'] = _NR_SRS_PACK
DESCRIPTOR.message_types_by_name['NR_SRS_INFO'] = _NR_SRS_INFO
DESCRIPTOR.message_types_by_name['RESULT'] = _RESULT

NR_SRS_PACK = _reflection.GeneratedProtocolMessageType('NR_SRS_PACK', (_message.Message,), dict(
  DESCRIPTOR = _NR_SRS_PACK,
  __module__ = 'ul_srs_est_pb2'
  # @@protoc_insertion_point(class_scope:NRpose.NR_SRS_PACK)
  ))
_sym_db.RegisterMessage(NR_SRS_PACK)

NR_SRS_INFO = _reflection.GeneratedProtocolMessageType('NR_SRS_INFO', (_message.Message,), dict(
  DESCRIPTOR = _NR_SRS_INFO,
  __module__ = 'ul_srs_est_pb2'
  # @@protoc_insertion_point(class_scope:NRpose.NR_SRS_INFO)
  ))
_sym_db.RegisterMessage(NR_SRS_INFO)

RESULT = _reflection.GeneratedProtocolMessageType('RESULT', (_message.Message,), dict(
  DESCRIPTOR = _RESULT,
  __module__ = 'ul_srs_est_pb2'
  # @@protoc_insertion_point(class_scope:NRpose.RESULT)
  ))
_sym_db.RegisterMessage(RESULT)


# @@protoc_insertion_point(module_scope)
